---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - "socialaggregator/aggregator/tests"
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    pep8:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
  - "spa/test"
  - "spa/gulpfile.js"
