

strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

ignore-paths:
  - node
  - spa
  - nginx
  - .idea
  - .git

pep8:
  full: true
  options:
    max-line-length: 119

mccabe:
  run: true

uses:
  - django
