branches:
  only:
  - master
  - develop

sudo: required

language: python

before_install:
  - cd socialaggregator/requirements/
install:
  - bash ../bin/install.sh
  - cd ../
script:
  - bash bin/test.sh
