version: '2'
services:
  node:
    build:
      context: .
      dockerfile: /node/Dockerfile
    volumes:
      - ./spa:/usr/src/spa
    command: 'sh /usr/src/spa/compile.sh'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - django
    ports:
      - "80:80"
    volumes:
      - ./socialaggregator/static:/usr/src/app/static
      - ./spa:/usr/src/spa
  django:
    build:
      context: ./socialaggregator/
      dockerfile: Dockerfile
    volumes:
      - ./spa:/usr/src/spa
      - ./socialaggregator/static:/usr/src/app/static
    expose:
        - "8000"
    links:
        - postgres
    command: sh run.sh

  postgres:
    image: postgres:9.3
