version: '2'
services:
  node:
    extends:
      file: docker-compose-abstract.yml
      service: base
    build:
      context: .
      dockerfile: /node/Dockerfile
    volumes:
      - ./spa:/usr/src/spa
    command: 'sh /usr/src/spa/compile.sh'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - django
    ports:
      - "80:80"
    volumes:
      - ./socialaggregator/static:/usr/src/app/static
      - ./spa:/usr/src/spa
      - ./docs/:/usr/src/docs/
  django:
    extends:
      file: docker-compose-abstract.yml
      service: base
    environment:
     - DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
     - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
     - SECRET_KEY=somesecretvalue
     - SOCIAL_AUTH_FACEBOOK_SECRET=${SOCIAL_AUTH_FACEBOOK_SECRET}
     - SOCIAL_AUTH_GITHUB_SECRET=${SOCIAL_AUTH_GITHUB_SECRET}
     - SOCIAL_AUTH_VK_OAUTH2_SECRET=${SOCIAL_AUTH_VK_OAUTH2_SECRET}
     - SOCIAL_AUTH_TWITTER_SECRET=${SOCIAL_AUTH_TWITTER_SECRET}
     - EMAIL_HOST_USER=${EMAIL_HOST_USER}
     - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
     - CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN}
    build:
      context: ./socialaggregator/
      dockerfile: Dockerfile
    volumes:
      - ./spa:/usr/src/spa
      - ./socialaggregator/static:/usr/src/app/static
    expose:
        - "8000"
    command: sh run.sh
