version: '2'
services:
  node:
    extends:
      file: docker-compose-abstract.yml
      service: base
    build:
      context: ./spa
      dockerfile: Dockerfile
    environment:
     - PORT=9000
     - BACKEND_HOST=http://api.socialaggregator.dev
    volumes:
      - ./spa:/usr/src/spa

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./socialaggregator/static:/usr/src/app/static
      - ./spa:/usr/src/spa
      - ./docs/:/usr/src/docs/

  django:
    extends:
      file: docker-compose-abstract.yml
      service: backend
    depends_on:
      - db
      - celery
    build:
      context: ./socialaggregator/
      dockerfile: Dockerfile
    volumes:
      - ./spa:/usr/src/spa
      - ./socialaggregator/static:/usr/src/app/static
    expose:
        - "8000"

  celery:
    extends:
      file: docker-compose-abstract.yml
      service: backend
    build:
      context: .
      dockerfile: celery/Dockerfile
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - "6379"

  db:
    image: postgres
    expose:
      - "5432"

  sentry:
    image: slafs/sentry
    environment:
     - SECRET_KEY=somethingsecret
     - SENTRY_URL_PREFIX=http://localhost:9000
     - SENTRY_INITIAL_TEAM=socialaggregatorteam
     - SENTRY_INITIAL_PROJECT=socialaggregator
     - SENTRY_INITIAL_KEY=public:secret
   command: /usr/local/bin/sentry_run prepare
