version: '2'
services:
  node:
    extends:
      file: docker-compose-abstract.yml
      service: base
    build:
      context: ./spa
      dockerfile: Dockerfile
    environment:
     - PORT=9000
     - BACKEND_HOST=http://api.socialaggregator.dev
    volumes:
      - ./spa:/usr/src/spa
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - django
    ports:
      - "80:80"
    volumes:
      - ./socialaggregator/static:/usr/src/app/static
      - ./spa:/usr/src/spa
      - ./docs/:/usr/src/docs/
  django:
    extends:
      file: docker-compose-abstract.yml
      service: base
    depends_on:
      - db
    environment:
     - DATABASE_URL=postgres://postgres@db/postgres
     - REDIS_URL=redis://redis:6379/0
     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
     - SECRET_KEY=somesecretvalue
     - DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
     - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
     - SOCIAL_AUTH_FACEBOOK_SECRET=${SOCIAL_AUTH_FACEBOOK_SECRET}
     - SOCIAL_AUTH_GITHUB_SECRET=${SOCIAL_AUTH_GITHUB_SECRET}
     - SOCIAL_AUTH_VK_OAUTH2_SECRET=${SOCIAL_AUTH_VK_OAUTH2_SECRET}
     - SOCIAL_AUTH_TWITTER_SECRET=${SOCIAL_AUTH_TWITTER_SECRET}
     - EMAIL_HOST=${EMAIL_HOST}
     - EMAIL_HOST_USER=${EMAIL_HOST_USER}
     - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
     - FRONTEND_URI=http://socialaggregator.dev/
     - FRONTEND_CONFIRMATION_URI=http://socialaggregator.dev/register/confirm
     - FRONTEND_RESET_PASSWORD_URI=http://socialaggregator.dev/password/reset/complete/
     - SENTRY_PRIVATE_DSN=http://public:secret@localhost:9000/2
    build:
      context: ./socialaggregator/
      dockerfile: Dockerfile
    volumes:
      - ./spa:/usr/src/spa
      - ./socialaggregator/static:/usr/src/app/static
    expose:
        - "8000"
  redis:
    image: redis
    expose:
      - "6379"

  db:
    image: postgres
    expose:
      - "5432"
